---

# configure ntp  
- hosts: servers
  remote_user: root

  roles:
    - ntp
  tags:
    - ntp

# configure zabbix agent
- hosts: zabbix
  remote_user: root

  roles:
    - zabbix_agent
  tags:
    - zabbix
